### ISSUE TITLE
Right CTRL automatically presses [Alt] in Emacs

### ISSUE THREAD

**Issue by timo-a** [MaxGyver83/neo2-llkh#36] opened 2020-11-13 08:14 UTC
Hi,

when I open emacs and press e.g. C-x (that hold down ctrl and then press x as well) and I use the right ctrl (left works!) Emacs shows C-M-x (M usually maps to [Alt]) as being pressed and acts accordingly (no such command).

Also the capslock key does not work as intended, I think it is mapped to C-u.

**Edit:** I'm using v0.5.1 (6b211f)  and Emacs 27.1

**Comment by MaxGyver83** [comment] 2020-11-13 09:25
Hi @timo-a ,

thanks for your report. I'll try to reproduce it.

**Comment by MaxGyver83** [comment] 2020-11-17 13:00
> when I open emacs and press e.g. C-x (that hold down ctrl and then press x as well) and I use the right ctrl (left works!) Emacs shows C-M-x (M usually maps to [Alt]) as being pressed and acts accordingly (no such command).

I can confirm this.

> Also the capslock key does not work as intended, I think it is mapped to C-u.

For me it works as expected (as a level 3 modifier). What happens when you enter for example `CapsLock+f`? When you hit `CapsLock` only, do you see `C-u` in Emacs's status bar?

**Comment by MaxGyver83** [comment] 2020-11-20 14:45
> when I open emacs and press e.g. C-x (that hold down ctrl and then press x as well) and I use the right ctrl (left works!) Emacs shows C-M-x (M usually maps to [Alt]) as being pressed and acts accordingly (no such command).

This bug does not occur in [version 0.4](https://github.com/MaxGyver83/neo2-llkh/releases/tag/v0.4). Maybe you can use it until this issue is fixed?
@fw623 : I suppose this bug was introduced with [this pull request](https://github.com/MaxGyver83/neo2-llkh/pull/24). Do you have an idea, how to fix it (without reverting your PR)?

**Comment by timo-a** [comment] 2020-11-23 19:18
When I press Capslock alone, nothing is shown in the status bar.
When I press Capslock-a, Capslock-s, Capslock-d, Capslock-f, Capslog-g (where "asdfg" mean what is printed on the physical keys, not a virtual mapping) on either "neo" or "qwertz" the following happens:

Capslock + | statusbar
-------|---
a| C-M-ß
s| `/` is typed out
d| C-u 7-
f| C-u 0-
g| `*` is typed out


I can confirm that right ctrl works in v0.4, however the Capslock bug occurs there as well

**Comment by fw623** [comment] 2020-11-24 21:45
> @fw623 : I suppose this bug was introduced with this pull request. Do you have an idea, how to fix it (without reverting your PR)?

Honestly, I don't know without trying out stuff. But I currently don't have time for that.

Though one (possibly key) difference I noticed is that in [master](https://github.com/MaxGyver83/neo2-llkh/blob/3370e05ca19adea60800a0b715093c0384bf76bd/src/main.c#L921) we call `handleSystemKey` before handling the neo modifiers. Whereas in [v0.4](https://github.com/MaxGyver83/neo2-llkh/blob/42a110116657fb57bcceba812dd33d53c86e88e3/src/main.c#L726) we handle `mod3` and `mod4` before looking at the system keys. Though quite a fair bit has changed about that handling in general, so that might not be the cause.


> When I press Capslock-a, Capslock-s, Capslock-d, Capslock-f, Capslog-g (where "asdfg" mean what is printed on the physical keys, not a virtual mapping) on either "neo" or "qwertz" the following happens: [...]

As for this, the keypresses that are sent is actually what I'd expect. `\` is `AltGr + ß` (= `Ctrl + Alt + ß`) on my keyboard (German QWERTZ) and `{`/`}` are on `AltGr + 7`/`AltGr + 0`. While `/` and `*` can be reached by just shifting. 

I remember that I had some problems in VSCode in Windows with `}` and `\` since they'd trigger a shortcut instead of typing the character. Maybe that's related to your situation.

Maybe it's worth looking into `sendChar` and trying around with how that's handled. A potential problem I see there is that the necessary modifier keys are pressed and then released once for the press and then again for the release. So maybe if we only send the modifiers on `keyDown` events (e.g. `if (!isKeyUp && altgr) sendDown(VK_RMENU, 56, false);` instead of `if (altgr) sendDown(VK_RMENU, 56, false);`). It could also be that some `isExtended` is incorrect in a `sendDown`/`sendUp` there.

**Comment by MaxGyver83** [comment] 2021-01-06 19:18
Fixed in [v0.5.2](https://github.com/MaxGyver83/neo2-llkh/releases/tag/v0.5.2)
Please re-open if it doesn't work as expected.

**Closed as completed by MaxGyver83** 2021-01-06 19:18 UTC
